services:
  backend1:
    build: ./backend
    container_name: backend1
    image: notes-project-backend
    ports:
      - "1717:1717"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mern-notes

  backend2:
    build: ./backend
    container_name: backend2
    image: notes-project-backend
    ports:
      - "1718:1717"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mern-notes

  frontend:
    build: ./frontend
    container_name: notes-frontend
    image: notes-project-frontend
    ports:
      - "4001:4001"
    depends_on:
      - backend1
      - backend2

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    ports:
      - "80:80"
    depends_on:
      - backend1
      - backend2
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro

volumes:
  mongo-data: